import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Category } from "../common/components/Category";
import { FloatingButton } from "../common/components/Buttons";
import { GetState } from "../common/hooks/getState";
import { BaseModal, ModalBody, ModalHeader } from "../common/components/Modals";
import { NomineeCard } from "../common/components/NomineeCard";

const Home: NextPage = () => {
	const state = GetState();

	return (
		<div>
			<Head>
				<title>Take Home Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h2 className={styles.pageTitle}>AWARDS 2022</h2>
				<div className={styles.categoriesContainer}>
					{state.isLoadingBallot ? (
						<div style={{ textAlign: "center" }}>Loading Ballots, please wait...</div>
					) : state.ballotsError ? (
						<div style={{ textAlign: "center" }}>An Error: {JSON.stringify(state.ballotsError)}</div>
					) : state.hasBallots ? (
						state.ballots.map((ballot) => (
							<Category
								key={ballot.id}
								ballot={ballot}
								onSelectNominee={state.onSelectNomineeCategory(ballot.id, ballot.title)}
								selectedNomineeCategory={state.selectedNomineeData.find(
									(item) => item.categoryId === ballot.id
								)}
							/>
						))
					) : (
						<div style={{ textAlign: "center" }}>No ballots found</div>
					)}
				</div>
				<FloatingButton
					disabled={!state.hasSelectedNominees}
					title={
						state.hasSelectedNominees ? "Click to submit your vote" : "Please select at least one nominee"
					}
					onClick={state.onSubmitVote}
				>
					{state.hasSelectedNominees ? "SUBMIT BALLOT" : "No Selection"}
				</FloatingButton>
				<BaseModal isOpen={state.isModalOpen} onDismiss={state.onCloseModal}>
					<ModalHeader modalTitle="Voting Successful!"></ModalHeader>
					<ModalBody>
						<div>
							<h3 className={styles.yourVoteTitle}>Your Votes</h3>

							{state.selectedNomineeData.map((item) => (
								<div key={item.categoryId}>
									<h4 className={styles.categoryTitle}>In {item.categoryTitle}</h4>
									<NomineeCard nominee={item.nominee} />
								</div>
							))}
						</div>
					</ModalBody>
				</BaseModal>
			</main>
		</div>
	);
};

export default Home;
